name: tinydb_client
version: 0.1.0
description: TinyDB Dart/Flutter client SDK for interacting with TinyDB collections and documents.
repository: https://github.com/cubetiqlabs/tinydb
publish_to: "none"

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  http: ^1.2.0
  meta: ^1.10.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
